# Setup
title:        cyq
tagline:      大概都是技术相关吧~
baseurl:      /
paginate:     5
locale:       "zh_CN"
encoding:     utf-8

# About/contact
author:
  name:       cyq
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown