# Site settings
title: cyq的梦呓
email: chyq@pku.edu.cn
description: Time
baseurl: ""
url: "https://yanqi-chen.github.io"

author:
  name     : 'cyq'
  email    : chyq@pku.edu.cn
  url      : https://yanqi-chen.github.io
  facebook : 
  twitter  : 

github: https://github.com/yanqi-chen
disqus_shortname: 
google_analytics: 

encoding: utf-8
locale: "zh_CN"

paginate: 2
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
kramdown:
  input: GFM
highlighter: rouge

permalink : /:title/
