# Site settings
title: CYQ Blog
SEOTitle: cyq的呓语 | CYQ Blog
header-img: img/cover-1.jpg
email: chyq@pku.edu.com
description: "是时候展现真正的技术了~"
keyword: "CYQ"
url: "https://yanqi-chen.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/Yanqi-Chen/Yanqi-Chen.github.io.git"


# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username:     
zhihu_username:   chen-yan-qi-53  
github_username:    Yanqi-Chen
twitter_username:   
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
timezone: Asia/Shanghai



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate, jemoji, jekyll-sitemap]


# License
license: 
  enable: true
  # "CC-BY-4.0", "CC-BY-SA-4.0", "CC-BY-NC-4.0", "CC-BY-ND-4.0", "CC-BY-NC-SA-4.0", "CC-BY-NC-ND-4.0"
  name: CC-BY-NC-SA-4.0 


# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
# disqus_username: 

# Netease settings
# netease_comment: false

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 9adf41631e4bec8c864f                            #生成的clientID
  clientSecret: a23b9d7c3d5acc132e717c7e71a0e9ad97c42f21    #生成的clientSecret
  repo: yanqi-chen.github.io    #仓库名称
  owner: yanqi-chen    #github用户名
  admin: yanqi-chen
  distractionFreeMode: true #是否启用类似FB的阴影遮罩

# Analytics settings
# Baidu Analytics 
ba_track_id: d3f41389e63d0fb6059a52f328eb0296

# Google Analytics
ga_track_id: 'UA-134047134-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto



# Sidebar settings
sidebar: false                           # whether or not using Sidebar.
sidebar-about-description: ""
sidebar-avatar: /img/avatar-hux-ny.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: true

# Visit count (Based on LeanCloud)
leancloud:
  enable: true
  app_id: 18VsSzL82aE3kCh2Vsv2tq84-gzGzoHsz
  app_key: SL6rsnTNNjJX4UJd1HCJrJI5

# Friends
friends: [
  {
    title: "qizhi",
    href: "http://qizhi.pkuml.org/"
  }
]
